#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'

$LOAD_PATH << File.join(File.dirname(__FILE__), '..', 'app', 'models')
require 'transient_key_store'

options = {
  :dir        => '/tmp/test/',
  :backtrace  => true,
  :log_output => true,
  :monitor    => true
}

Daemons.run_proc('transient_key_store', options) {
  TransientKeyStore.run_server
}
